export type ToolCategory = 'benefits' | 'clarity';

export interface ToolDefinition {
	id: string;
	route: string;
	question: string;
	description: string;
	keywords: string[];
	category: ToolCategory;
	icon: string;
}

export const tools: ToolDefinition[] = [
	{
		id: 'screener',
		route: '/tools/screener',
		question: 'What programs might help you?',
		description:
			'Food, health coverage, phone, energy, school meals — see which California programs you may qualify for.',
		keywords: [
			'food stamps',
			'SNAP',
			'CalFresh',
			'EBT',
			'Medi-Cal',
			'Medicaid',
			'benefits',
			'qualify',
			'programs',
			'assistance',
			'income',
			'household',
			'free food',
			'health insurance',
			'low income',
			'ALICE',
			'CalWORKs',
			'WIC',
			'free lunch',
			'school meals',
			'phone assistance',
			'Lifeline',
			'energy bill',
			'LIHEAP',
			'help paying bills',
			'do I qualify',
			'what can I get',
			'what programs am I eligible for',
		],
		category: 'benefits',
		icon: 'ShieldCheck',
	},
	{
		id: 'recertification',
		route: '/tools/recertification',
		question: 'When does your renewal come up?',
		description: 'Get a calendar reminder before your SNAP or Medicaid recertification deadline.',
		keywords: [
			'recertification',
			'renewal',
			'deadline',
			'SNAP',
			'Medicaid',
			'CalFresh',
			'Medi-Cal',
			'calendar',
			'expiring',
			'benefits ending',
			'certification period',
			'reminder',
			'renewal date',
			'when do I renew',
			'losing benefits',
			'cut off',
		],
		category: 'benefits',
		icon: 'CalendarClock',
	},
	{
		id: 'cliff-calculator',
		route: '/tools/cliff-calculator',
		question: 'Got a raise — do you actually come out ahead?',
		description: 'See what a higher income does to your benefits before you decide.',
		keywords: [
			'benefits cliff',
			'raise',
			'I got a raise',
			'got a raise',
			'income increase',
			'lose benefits',
			'will I lose my benefits',
			'CalFresh',
			'Medi-Cal',
			'job offer',
			'new job offer',
			'new job',
			'starting a new job',
			'promotion',
			'higher pay',
			'more money',
			'income went up',
			'will I lose',
			'better off',
			'worse off',
			'net change',
			'pay raise',
			'earning more',
			'cliff effect',
			'income cliff',
		],
		category: 'benefits',
		icon: 'TrendingUp',
	},
	{
		id: 'emergency-fund',
		route: '/tools/emergency-fund',
		question: 'How many months of runway do you actually have?',
		description: 'Check your emergency fund against your real monthly costs.',
		keywords: [
			'emergency fund',
			'savings',
			'runway',
			'months',
			'expenses',
			'cushion',
			'cash',
			'buffer',
			'how long will my money last',
			'rainy day fund',
			'nest egg',
			'how much should I save',
			'three months',
			'six months',
		],
		category: 'clarity',
		icon: 'Umbrella',
	},
	{
		id: 'compound-interest',
		route: '/tools/compound-interest',
		question: 'How does a small amount grow over time?',
		description:
			'See the split between what you put in and what interest added — at any time horizon.',
		keywords: [
			'compound interest',
			'savings growth',
			'investing',
			'interest',
			'future value',
			'time',
			'small amount',
			'grow money',
			'how much will I have',
			'retirement',
			'APY',
			'return',
			'over time',
		],
		category: 'clarity',
		icon: 'LineChart',
	},
	{
		id: 'debt-growth',
		route: '/tools/debt-growth',
		question: 'Is your debt growing faster than your savings?',
		description: 'Compound interest runs in both directions. See them on the same chart.',
		keywords: [
			'debt',
			'credit card',
			'APR',
			'interest rate',
			'savings vs debt',
			'compound',
			'growing faster',
			'pay off',
			'minimum payment',
			'debt spiral',
			'loan',
			'balance',
			'interest',
		],
		category: 'clarity',
		icon: 'TrendingDown',
	},
	{
		id: 'savings-commitment',
		route: '/tools/savings-commitment',
		question: 'Want to save more — what would actually make it happen?',
		description:
			'Write one specific savings commitment in your own words and get a calendar reminder.',
		keywords: [
			'savings goal',
			'commitment',
			'habit',
			'calendar',
			'reminder',
			'save more',
			'plan',
			'start saving',
			'set a goal',
			'accountability',
		],
		category: 'clarity',
		icon: 'PiggyBank',
	},
	{
		id: 'tip-calculator',
		route: '/tools/tip-calculator',
		question: 'What do servers in your state actually earn?',
		description: 'Split the check and see the wage context behind the tip screen.',
		keywords: [
			'tip',
			'tipping',
			'server',
			'restaurant',
			'split check',
			'wage',
			'how much to tip',
			'bill',
			'service',
			'gratuity',
			'tip amount',
		],
		category: 'clarity',
		icon: 'Receipt',
	},
	{
		id: 'tax-clarity',
		route: '/tools/tax-clarity',
		question: 'What does a deduction actually save you?',
		description:
			'See the difference between a deduction, a credit, and what your refund really means.',
		keywords: [
			'tax deduction',
			'tax credit',
			'refund',
			'taxes',
			'understand my taxes',
			'how do taxes work',
			'what is a tax deduction',
			'do I owe taxes',
			'how much tax do I pay',
			'filing',
			'W-2',
			'return',
			'itemize',
			'standard deduction',
			'how much do I save',
			'1099',
			'withholding',
			'tax bracket',
		],
		category: 'clarity',
		icon: 'FileText',
	},
	{
		id: 'document-checklist',
		route: '/tools/document-checklist',
		question: 'What do you need to bring?',
		description:
			'One de-duplicated list of documents across every program you are applying to.',
		keywords: [
			'documents',
			'checklist',
			'what to bring',
			'ID',
			'proof of income',
			'applying for benefits',
			'paperwork',
			'identification',
			'application',
			'documentation',
		],
		category: 'benefits',
		icon: 'ClipboardList',
	},
	{
		id: 'myth-quiz',
		route: '/tools/myth-quiz',
		question: "What's actually true about benefits?",
		description:
			"Five things most people believe about benefits programs — and what the data shows.",
		keywords: [
			'myths',
			'benefits myths',
			'SNAP myths',
			'misconceptions',
			'quiz',
			'facts',
			'immigration',
			'work requirements',
			'is it true that',
			'I heard',
		],
		category: 'benefits',
		icon: 'HelpCircle',
	},
	{
		id: 'myth-quiz-2',
		route: '/tools/myth-quiz-2',
		question: 'How many money rules are actually true?',
		description:
			'Ten things most people believe about taxes, credit, tipping, and compound interest.',
		keywords: [
			'money myths',
			'quiz',
			'taxes myths',
			'credit score myths',
			'tipping myths',
			'compound interest myths',
			'misconceptions',
			'personal finance quiz',
			'is it true',
		],
		category: 'clarity',
		icon: 'HelpCircle',
	},
	{
		id: 'work-hours',
		route: '/tools/work-hours',
		question: 'Where does each hour of work actually go?',
		description:
			'See your pay broken down by taxes and take-home — in time, not just dollars.',
		keywords: [
			'paycheck',
			'understand my paycheck',
			'where does my money go',
			'how much do I actually make',
			'take home pay',
			'taxes',
			'take-home',
			'hourly rate',
			'real wage',
			'federal tax',
			'FICA',
			'state tax',
			'net pay',
			'gross pay',
			'how much do I keep',
			'after tax',
			'social security',
		],
		category: 'clarity',
		icon: 'Clock',
	},
	{
		id: 'guide',
		route: '/tools/guide',
		question: 'Not sure where to start?',
		description: "Pick the situation that fits — we'll show you the right tools.",
		keywords: ['not sure', 'where to start', 'help me find', 'guide', 'questionnaire'],
		category: 'benefits',
		icon: 'Compass',
	},
];

export const benefitsTools = tools.filter((t) => t.category === 'benefits' && t.id !== 'guide');
export const clarityTools = tools.filter((t) => t.category === 'clarity');
